### PR TITLE
Russian translate (almost completely)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by juliand665** [comment]
Thanks for this! Should I wait until you've completed the last 3 translations? Is there something I can do to help you with those?

**Comment by ghost** [comment]
%1$s & %2$s - what this?

**Comment by juliand665** [comment]
Ah. Those are the more flexible form of the regular `%s`. When you have multiple `%s`, you can't change their order. `%1$s`, `%2$s`, etc. solve this problem by specifying the position, so if you change their order, they will still get the same values.

**Comment by ghost** [comment]
I need to understand, %1$s and  %2$s -- (what a word here?)
If you (all) wrote, which means %1$s and so on, then all translators would know how to translate sentences without checking the Minecraft

**Comment by juliand665** [comment]
Yeah, it would of course be nice to know without having to check what the placeholders (`%s`, `%1$s`, …) will be replaced with, but I can't just write it into the lang file unfortunately. I think they make sense in context though. Which specific key are you asking about? (e.g. `"gui.solcarrot.food_book.fraction"` is a key, `"message.solcarrot.finished.chat"` is a key, …)

**Pull request closed without merging**
