### PR TITLE
Fix for any mod incompatible that also adding tooltips

### PR DESCRIPTION
**Pull request by murao-kun**
Should resolve any tooltip issue that added by other mods. Have some in my own modpack, so I made a fix for that and people that can have same issue as well.

### CODE REVIEW

**Comment by juliand665** [comment]
Huh! Can you show an example of this issue?

**Comment by murao-kun** [comment]
Without fix: 
image
Tasted is renamed lang file in SoL carrot edition. (Should be at very bottom and only above mod id)
Other stats is SoL sweet potato edition. (Should be above Tasted)
With fix:
image

**Comment by juliand665** [comment]
Ah, so it's overwritten by other greedy mods if it gets called too early, and lowering the priority ensures it's called late enough to show up?

**Comment by murao-kun** [comment]
Actually mods that not assigning their tooltip priority using NORMAL option by default (And sorting by mod id instead). This will make SoL using lower priority to be called late enough to be last one before mod id tooltip added by Jei or other mod. I hope that will you consider to accept this PR and save you from any related to this issues. :)

**Comment by juliand665** [comment]
Ah right, it's there in both tooltips, just lower in the second. Looks good to me!

**Comment by juliand665** [comment]
Looks like `LOWER` actually doesn't exist for me, so I just replaced it with `LOW`. Hope that works!

**Comment by murao-kun** [comment]
You are right! Sorry, just got a cold and made this change with high body temperature. My bad at misspelling. xD

**Comment by juliand665** [comment]
Haha all good! Thanks for the contribution and get well soon :)

**Comment by murao-kun** [comment]
Thank you!

**Pull request merged**
